apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:         # minimum CPU or memory to be avali for the container in a pod to start
        memory: "64Mi"
        cpu: "2"
      limits:           #  maximum amount of a resource (CPU or memory) that a pod can use 
        memory: "128Mi"
        cpu: "4"
  
  
  # - name: log-aggregator
  #   image: images.my-company.example/log-aggregator:v6
  #   resources:
  #     requests:
  #       memory: "64Mi"
  #       cpu: "250m"
  #     limits:
  #       memory: "128Mi"
  #       cpu: "500m"


