apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: nginx
    resources:
      requests:         # Requests are the minimum guaranteed amount of a resource that is reserved for a container.
        memory: "64Mi"
        cpu: "2"
      limits:           # Kubernetes defines Limits as the maximum amount of a resource to be used by a container. This means that the container can never consume more than the memory amount or CPU amount indicated.
        memory: "128Mi"
        cpu: "4"
  
  
  # - name: log-aggregator
  #   image: images.my-company.example/log-aggregator:v6
  #   resources:
  #     requests:
  #       memory: "64Mi"
  #       cpu: "250m"
  #     limits:
  #       memory: "128Mi"
  #       cpu: "500m"


