apiVersion: v1
kind: Pod
metadata:
  name: centos-pod
spec:
  containers:
  - name: centos-container
    image: centos:7
    command: ["sleep", "10000"]
    envFrom:
      - secretRef:
          name: secret-demo

---

apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
data:
  usr: YWRtaW4K
  password: YWRtaW4xMjMK
  

  


